# Generated by Django 6.0.2 on 2026-04-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_frequency_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks')], default='days', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_frequency_value',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
