# Generated by Django 6.0.2 on 2026-04-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_budget_alter_user_shopping_frequency_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dietary_restrictions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
